### PR TITLE
Now the derivative can be applied either to the error or only to the output

### PR DESCRIPTION
**Pull request by rafaelsaback**
I've made the changes we have discussed, and basically, now the user can choose between aplying the derivative action to the error or only to the output.

As default, I followed Jakob suggestion and the derivative action is applied to the error.

### CODE REVIEW

**Comment by doudou** [comment]
@saarnold: please wait a little bit before merging a PR, to let people comment on it.

I have a problem with enabling the new behaviour by default. It will (silently) change the behaviour of all existing controllers that have a D part.

**Comment by saarnold** [comment]
@doudou This PR was just extending the PR in rock-control/control-motor_controller#2, the discussion should be there.
And I hope that @ajishbabu may adds himself as maintainer of this library :)

**Comment by ajishbabu** [comment]
i will add myself as maintainer. But currently I have no running system/setup where I could test the controllers. Later I will try and setup some sort of testsuite.  In the mean time, if someone has tested it in on a running system, do let me know.

**Comment by doudou** [comment]
@saarnold ... my mistake.

**Pull request merged**
